config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :shopping_lists
  resources :foods, only: [:index, :new, :create, :destroy]

  resources :recipes, only: %i[index new create show destroy] do
    resources :recipe_foods, only: %i[new create]
  end

  root 'users#index'
  get '/public_recipes', to: 'public_recipes#index'
  
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user, class_name: 'User'
  has_many :recipe_foods, class_name: 'RecipeFood', foreign_key: 'recipe_id', dependent: :destroy

  validates :name, presence: true, length: { maximum: 50 }
  validates :preparation_time, numericality: { only_integer: true }, comparison: { greater_than_or_equal_to: 1 }
  validates :cooking_time, numericality: { only_integer: true }, comparison: { greater_than_or_equal_to: 1 }
  validates :description, presence: true, allow_blank: true
  validates :public, inclusion: { in: [true, false] }

  def getfoods(id)
    food_list = []
    recipe_foods = RecipeFood.where(recipe_id: id)

    recipe_foods.each do |foods|
      Food.where(id: foods.food_id).each do |food|
        food_list.push(food)
      end
    end
    food_list
  end

  def total_price(food_list)
    total = 0
    food_list.each do |food|
      RecipeFood.where(food_id: food.id).each do |recipe_food|
        @single_food_price = food.price * recipe_food.quantity
      end
      total += @single_food_price
    end
    total
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: %i[show edit update destroy]

  # GET /recipes or /recipes.json
  def index
    @recipes = Recipe.order(created_at: :desc).all
  end

  # GET /recipes/1 or /recipes/1.json
  def show
    @recipe = Recipe.find(params[:id])
    @recipe_foods = @recipe.recipe_foods.includes(:food)
    @user = @recipe.user
  end

  # GET /recipes/new
  def new
    @recipe = Recipe.new
  end

  # POST /recipes or /recipes.json
  def create
    @recipe = current_user.recipes.new(recipe_params)

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to recipes_url(@recipe), notice: 'Recipe was successfully created.' }
        format.json { render :show, status: :created, location: @recipe }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1 or /recipes/1.json
  def destroy
    @recipe.destroy

    respond_to do |format|
      format.html { redirect_to recipes_url, notice: 'Recipe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_recipe
    @recipe = Recipe.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def recipe_params
    params.require(:recipe).permit(:name, :preparation_time, :cooking_time, :description, :public)
  end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_form.html.erb
<%= form_with(model: recipe) do |form| %>
  <% if recipe.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
        <% recipe.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :preparation_time, style: "display: block" %>
    <%= form.text_field :preparation_time %>
  </div>

  <div>
    <%= form.label :cooking_time, style: "display: block" %>
    <%= form.text_field :cooking_time %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :public, style: "display: block" %>
    <%= form.check_box :public %>
  </div>


  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/recipes/_recipe.html.erb
<div id="<%= dom_id recipe %>">
  
</div>

app/views/recipes/edit.html.erb
<h1>Editing recipe</h1>

<%= render "form", recipe: @recipe %>

<br>

<div>
  <%= link_to "Show this recipe", @recipe %> |
  <%= link_to "Back to recipes", recipes_path %>
</div>

app/views/recipes/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Recipes</h1>


<div id="recipes">
  <% @recipes.each do |recipe| %>
    <%= render recipe %>
  <% end %>
</div>
<button type="button" class="Delete-recipe">
<%= link_to "New recipe", new_recipe_path, class: "nav-link" %>
          </button>
        



<a href="/recipes/new" class="add_new_recipe">Add new recipe</a>
</div>
<div class="all-recipes-container">
  <% @recipes.each do |recipe| %>

      <div class="recipe-container">
        <div class="recipe-name"> 
          <a href="/recipes/<%= recipe.id%>" class="name-recipe"> 
            <h3><%= recipe.name %></h3>
          </a>  
  
          <button type="button" class="Delete-recipe">
            <%= link_to 'Details', recipe_path(recipe), method: :get, class: "nav-link" %>
          </button>
        
          <%= button_to "REMOVE",recipe_path(id: recipe.id), method: :delete, class: 'Delete-recipe'  %>
        </div>
        <div class="recipe-description">
          <p class="description"><%= recipe.description %></p>
        </div>
      </div>

  <%end%>
</div>

app/views/recipes/new.html.erb
<h1>New recipe</h1>

<%= render "form", recipe: @recipe %>

<br>

app/views/recipes/show.html.erb
<div class="container">
  <div>
  <h2> <%= @recipe.name %></div>
  </h2>
  <div>
    <div>
      <h5>Preparation time : <%= @recipe.preparation_time %></h5>
    </div>
    <div>
      <h5>Public : <%= @recipe.public %></h5>
    </div>
  </div>
  <div>
    <h5>Cooking time : <%= @recipe.cooking_time %></h5>
  </div>
  <div>
    <div>
      <%= link_to 'Generate shopping list', shopping_lists_path, class: "btn btn-primary" %>
    </div>
    <% if @recipe.user == current_user %>
      <div class="add_ing">
        <%= link_to 'Add ingredient', new_recipe_recipe_food_path(@recipe.id), class: "btn btn-primary" %>
      </div>
    <% end %>
  </div>
  <table class="table">
    <thead>
    <tr>
      <th scope="col">Food</th>
      <th scope="col">Quantity</th>
      <th scope="col">Value</th>
      <th scope="col">Action</th>
    </tr>
    </thead>
    <tbody>
    <% @recipe_foods.each do |recipe_food| %>
      <tr>
        <td><%= recipe_food.food.name %></td>
        <td><%= recipe_food.quantity %> <%= recipe_food.food.measurement_unit %></td>
        <td>$<%= recipe_food.quantity * recipe_food.food.price %></td>
        <td>
          <div>
            <div>
              <%= button_to 'Modify', method: :put, class: "btn btn-primary" %>
            </div>
            <% if can? :destroy, recipe_food.food %>
              <div>
                <%= button_to 'Remove', method: :delete, class: "btn btn-danger" %>
              </div>
            <% end %>
          </div>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>