config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :shopping_lists
  resources :foods, only: [:index, :new, :create, :destroy]

  resources :recipes, only: %i[index new create show destroy] do
    resources :recipe_foods, only: %i[new create]
  end

  root 'users#index'
  get '/public_recipes', to: 'public_recipes#index'
  
end

app/models/recipe_food.rb
class RecipeFood < ApplicationRecord
  belongs_to :recipe, class_name: 'Recipe', foreign_key: 'recipe_id'
  belongs_to :food, class_name: 'Food', foreign_key: 'food_id'

  validates :quantity, presence: true, numericality: { only_integer: true }, comparison: { greater_than_or_equal_to: 1 }
end

app/controllers/recipe_foods_controller.rb
class RecipeFoodsController < ApplicationController
  before_action :set_recipe_food, only: %i[show edit update destroy]

  # GET /recipes_foods or /recipes_foods.json
  def index
    @recipe_foods = RecipeFood.all
  end

  # GET /recipes_foods/1 or /recipes_foods/1.json
  def show; end

  # GET /recipes_foods/new
  def new
    @recipe_food = RecipeFood.new
    @recipe = Recipe.find(params[:recipe_id])
    @foods = Food.where(user_id: current_user.id)
  end

  # POST /recipes_foods or /recipes_foods.json
  def create
    @foods = Food.where(user_id: current_user.id)
    @food = Food.find(recipe_food_params['food'])
    @recipe = Recipe.find(params[:recipe_id])
    @recipe_food = RecipeFood.new(quantity: recipe_food_params['quantity'].to_i, food: @food, recipe: @recipe)

    respond_to do |format|
      if @recipe_food.save
        format.html { redirect_to recipes_path, notice: 'Recipes food was successfully created.' }
        format.json { render :show, status: :created, location: @recipes_foods }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @recipes_food.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes_foods/1 or /recipes_foods/1.json
  def destroy
    @recipe_food.destroy

    respond_to do |format|
      format.html { redirect_to recipesFoods_url, notice: 'Recipes food was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_recipe_food
    @recipe_food = RecipesFood.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def recipe_food_params
    params.require(:recipe_food).permit(:food, :quantity)
  end
end

app/helpers/recipe_foods_helper.rb
module RecipeFoodsHelper
end

app/views/recipe_foods/_form.html.erb
<%= form_with model: @recipe_food, url: recipe_recipe_foods_url, method: :post do |form| %>
  <div class="d-flex flex-column align-items-center">
  <div class= "d-flex flex-column align-items-center w-75 mb-3">
     <%= form.number_field :quantity, Placeholder: "Quantity", class: "form-control w-75 mb-3" %>
   <%= form.select :food, @foods&.map {|food| [food.name, food.id]}, class: "form-select w-75 mb-3" %>
     <%= form.submit class: "btn btn-primary" %>
   </div>
   </div>
 <% end %>
 

app/views/recipe_foods/_recipe_food.html.erb
<div id="<%= dom_id recipe_food %>">
  
</div>

app/views/recipe_foods/edit.html.erb
<h1>Editing recipe food</h1>

<%= render "form", recipe_food: @recipe_food %>

<br>

<div>
  <%= link_to "Show this recipe food", @recipe_food %> |
  <%= link_to "Back to recipe foods", recipe_foods_path %>
</div>

app/views/recipe_foods/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Recipes foods</h1>

<div id="recipe_foods">
  <% @recipe_foods.each do |recipe_food| %>
    <%= render recipe_food %>
    <p>
      <%= link_to "Show this recipes food", recipe_food %>
    </p>
  <% end %>
</div>

<%= link_to "New recipes food", new_recipeFood_path %>

app/views/recipe_foods/new.html.erb
<h1 class="text-center">New recipes food</h1>

<%= render "form", recipe_food: @recipes_food %>

<br>

app/views/recipe_foods/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @recipe_food %>

<div>
  <%= link_to "Edit this recipe food", edit_recipe_food_path(@recipe_food) %> |
  <%= link_to "Back to recipe foods", recipe_foods_path %>

  <%= button_to "Destroy this recipe food", @recipe_food, method: :delete %>
</div>